version: 2.1

orbs:
  gh: circleci/github-cli@1.0
  sre: tracktor/ci-tools@0.1.5

references:
  deploy_context: &deploy_context
    - github

executors:

  test-build:
    docker:
      - image: cimg/python:3.10-browsers

  build-docker:
    docker:
      - image: cimg/base:current

jobs:

  run-tests:

    executor: test-build
    steps:
      - checkout
      - sre/run-python-tests

  bump-version:
    executor: test-build
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Adding github.com to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Create release
          command: bash .circleci/scripts/release.sh
      - store_artifacts:
          path: dist
      - save_cache:
          name: Saving wheel
          key: proj-{{ checksum "pyproject.toml" }}
          paths:
            - dist/

  build-docker:
    executor: build-docker
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Load VERSION
          command: echo 'export VERSION=$(git tag -l --sort=-creatordate | head -n 1)' >> $BASH_ENV
      - sre/build-docker:
          image_name: 'andarius/track-utils'
          version: ${VERSION}
          latest_version: 'latest'
          registry_pwd: $DOCKER_PWD
          registry_user: $DOCKER_USER
          build_params: "--build-arg version=${VERSION}"
          publish: true


workflows:

  tests-bump:
    jobs:
      - run-tests:
          filters:
            tags:
              ignore: /.*/
      - bump-version:
          requires: [ run-tests ]
          context: *deploy_context
          filters:
            tags:
              only: /.*/
            branches:
              only: /^master$/

  publish:
    jobs:
      - build-docker:
          context: *deploy_context
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
