version: 2.1

orbs:
  gh: circleci/github-cli@1.0


executors:
  test-build:
    docker:
      - image: cimg/python:3.10-browsers

jobs:

  run-tests:
    executor: test-build
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install python dependencies
          command: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Running type checking
          command: poetry run pyright
      - run:
          name: Run tests
          command: |
            poetry run pytest -vv --junitxml=tests/junit.xml
      - run:
          name: Generating coverage
          command: |
            poetry run coverage xml -o tests/coverage.xml
            poetry run coverage html
      - store_test_results:
          path: tests
      - store_artifacts:
          path: htmlcov

  bump-version:
    executor: test-build
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Adding github.com to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Create release
          command: bash .circleci/scripts/release.sh
      - store_artifacts:
          path: dist
      - save_cache:
          name: Saving wheel
          key: proj-{{ checksum "pyproject.toml" }}
          paths:
            - dist/

workflows:

  run-tests:
    jobs:
      - run-tests:
          filters:
            tags:
              ignore: /.*/
      - bump-version:
          requires: [ run-tests ]
          filters:
            tags:
              only: /.*/
            branches:
              only: /^master$/
